/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Wed Mar 13 00:24:30 2019. */

#include "RobotCmd.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Hello_fields[2] = {
    PB_FIELD(  1, BYTES   , REQUIRED, STATIC  , FIRST, Hello, message, message, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
