/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.3 at Wed Mar 13 00:24:30 2019. */

#ifndef PB_ROBOTCMD_PB_H_INCLUDED
#define PB_ROBOTCMD_PB_H_INCLUDED
#include <pb.h>

#include "generator/proto/nanopb.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(43) Hello_message_t;
typedef struct _Hello {
    Hello_message_t message;
/* @@protoc_insertion_point(struct:Hello) */
} Hello;

/* Default values for struct fields */

/* Initializer values for message structs */
#define Hello_init_default                       {{0, {0}}}
#define Hello_init_zero                          {{0, {0}}}

/* Field tags (for use in manual encoding/decoding) */
#define Hello_message_tag                        1

/* Struct field encoding specification for nanopb */
extern const pb_field_t Hello_fields[2];

/* Maximum encoded size of messages (where known) */
#define Hello_size                               45

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define ROBOTCMD_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
